In [18]:
# 2개의 입력을 받는 3개의 뉴런
# 편향, 활성화 함수가 없는 간단한 신경망을 만들어 보자.

import numpy as np
X = np.array([1, 2])  # 입력값은 2개
W = np.array([  # 입력값 2개를 뉴런 3개가 받음.
              [1, 3, 5],  # 입력값에 대한 각각의 가중치 행렬  # 입력값 1에 대한 가중치
              [2, 4, 6]  # 입력값 2에 대한 가중치
])

Y = np.dot(X, W)
# 결과값 계산
# 행렬의 내적(행렬곱) 이용
# 입력값과 가중치의 곱의 합

In [19]:
print(X.shape)
print(W.shape)
print(Y.shape)
print(Y)

(2,)
(2, 3)
(3,)
[ 5 11 17]


In [20]:
# 3층으로 된 신경망을 구현해보자.
# 입력값 : 2개
# 은닉층 1층 : 뉴런 3개
# 은닉층 2층 : 뉴런 2개
# 출력층 3층 : 뉴런 2개

# 뉴런의 갯수를 정하는 건 내 마음대로
# 출력층은 클래스의 갯수대로

In [21]:
# a : 가중입력
# z : 각 층 별로 활성화함수까지 끝낸 출력값 이라고 하자.

# 입력 - 1층 과정
# 은닉층 1층 : 뉴런 3개
X = np.array([1.0, 0.5])
# 입력값 : 2개 ; 1*2 행렬
W1 = np.array([
               [0.1, 0.3, 0.5],
               [0.2, 0.4, 0.6]
])
# 입력값 - 1층 가중치 ; 2*3 행렬
B1 = np.array([0.1, 0.2, 0.3])
# 입력값 - 1층 편향 ; 1*3 행렬

# 활성화함수를 취하기 전인 가중입력값을 구해보자.
A1 = np.dot(X, W1) + B1

# 1층의 가중입력값 출력
print(A1)

# 활성화함수를 씌워보자.
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# 활성화함수를 취한 1층의 결과물
Z1 = sigmoid(A1)
print(Z1)
print(Z1.shape)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
(3,)


In [22]:
# 이번에는 1층 - 2층 과정
# 은닉층 2층 : 뉴런 2개
# 여기서는 1층의 출력이 2층의 입력이 된다.
W2 = np.array([
               [0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]
])
# 2층의 가중치 ; 3*2 행렬

B2 = np.array([0.1, 0.2])
# 2층의 편향 ; 1*2 행렬

print(Z1.shape)
print(W2.shape)
print(B2.shape)

# 행렬곱(내적)이 된다는 것 확인.

# 이제 활성화함수에 넣기전인
# 가중입력값 구하기
A2 = np.dot(Z1, W2) + B2
print(A2.shape)

# 활성화함수에 넣자.
Z2 = sigmoid(A2)
print(Z2.shape)
print(Z2)
# 이게 바로 2층에서의 활성화함수까지 취한 출력값

(3,)
(3, 2)
(2,)
(2,)
(2,)
[0.62624937 0.7710107 ]


In [23]:
# 이번에는 2층 - 3층 과정
# 은닉층 3층 : 뉴런 2개
# 여기서는 2층의 출력이 3층의 입력이 된다.
W3 = np.array([
               [0.1, 0.3],
               [0.2, 0.4]
])
# 3층의 가중치 ; 2*2 행렬

B3 = np.array([0.1, 0.2])
# 3층의 편향 ; 1*2 행렬
print(Z2.shape)
print(W3.shape)
print(B3.shape)

# 행렬의 곱(내적) 되는 것 확인

# 활성화함수에 넣기 전 값인 가중입력값 구하기
A3 = np.dot(Z2, W3) + B3

# 활성화함수에 넣어서 최종 출력값 확인
# 은닉층에서는 sigmoid 활성화 함수를 사용했지만
# 출력층에서는 항등함수, 교차 엔트로피(cross entropy), softmax 함수를 사용해서 최종 결과를 낸다.

# 여기는 입력값을 그대로 출력하는 항등함수를 활용해보자.
def identity_function(x):
  return x
Y = np.dot(A3, W3) + B3
print(Y)
# 이게 바로 맨 처음의 x1, x2의 입력값이
# 3개의 신경망 층을 지나서(2개의 은닉층, 1개의 출력층)
# 최종적으로 출력된 값

(2,)
(2, 2)
(2,)
[0.27093853 0.57355976]


In [26]:
# 이제 최종 구현에 대한 정리
# 은닉층의 활성화 함수, 출력층의 결과를 내기 위한 활성화 함수 다름

def init_network():
  network = {}
  # 신경망
  # 신경망의 가중치, 편향을 담은 딕셔너리를 출력하는 함수
  '''
  입력값 : 2개
  1층 은닉층 - 뉴런 3개
  가중치 : 2*3 행렬
  편향 : 1*3 행렬

  2층 은닉층 - 뉴런 2개
  가중치 : 3*2 행렬
  편향 : 1*2 행렬

  3층 출력층 - 뉴런 2개
  가중치 : 2*2 행렬
  편향 : 1*2 행렬  
  '''
  
  network["W1"] = np.array([
                            [0.1, 0.3, 0.5],
                            [0.2, 0.4, 0.6]
  ])
  network["b1"] = np.array([0.1, 0.2, 0.3])
  network["W2"] = np.array([
                            [0.1, 0.4],
                            [0.2, 0.5],
                            [0.4, 0.6]
  ])
  network["b2"] = np.array([0.1, 0.2])
  network["W3"] = np.array([
                            [0.1, 0.3],
                            [0.2, 0.4]
  ])
  network["b3"] = np.array([0.1, 0.2])

  return network

In [27]:
def forward(network, x):
  # 신경망의 가중치, 편향을 담은 network 객체와
  # 입력값 x를 입력하면
  # 3층 신경망을 총 거친 후의
  # 최종 출력값 return
  W1, W2, W3 = network["W1"], network["W2"], network["W3"]
  b1, b2, b3 = network["b1"], network["b2"], network["b3"]
  
  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)

  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)
  
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)
  
  return y

In [28]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31856586 0.70149544]


In [29]:
# 이게 바로 입력값 2개 1.0과 0.5를 넣었을 때
# 3층 신경망을 거쳐서 나온
# 최종 출력값

In [30]:
# 여기까지가 신경망의 순방향 구현!
# 이렇게 numpy의 array만 이용해서도 신경망을 만들 수 있다.
# tensorflow와 keras를 이용하는 것은 뒤에서!