# 다차원 배열

## 배열
- 숫자의 집합
- numpy 모듈

In [4]:
import numpy as np
A = np.array([1, 2, 3, 4])
print("배열의 원소 : {}".format(A))
print("배열의 차원수 : {}".format(A.ndim))
print("배열의 모양 : {}".format(A.shape))

배열의 원소 : [1 2 3 4]
배열의 차원수 : 1
배열의 모양 : (4,)


In [5]:
# 1차원 배열

In [6]:
B = np.array([
              [1, 2],
              [3, 4],
              [5, 6]
])

print(B)
print(B.ndim)  # 차원수
print(B.shape)  # 모양(shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [7]:
# 2차원 배열

## 행렬의 내적(행렬 곱)
- np.dot(A, B)

In [12]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])
B = np.array([
              [5, 6],
              [7, 8]
])

print(A.shape)
print(B.shape)

(2, 3)
(2, 2)


In [14]:
# print(np.dot(A, B))  # shape가 맞아야 한다.
print(np.dot(B, A))

[[29 40 51]
 [39 54 69]]


In [10]:
# 행렬의 곱은 교환법칙이 성립하지 않는다.

In [16]:
C = np.array([
              [1, 2],
              [3, 4]
])

# print(np.dot(A, C))  # (2, 3) (2, 2)는 내적이 되지 않는다.

In [17]:
print(np.dot(C, A))  # (3, 2) (2, 2)는 내적이 된다.

[[ 9 12 15]
 [19 26 33]]


In [18]:
# 행렬의 곱, 행렬의 내적
# 첫번째 행렬의 1번째 차원의 원소 수 = 두번째 행렬의 0번재 차원의 원소 수

In [19]:
# 차원수가 달라도 계산은 가능하다.
# 행렬 shape만 맞으면 된다.

In [20]:
A = np.array([
              [1, 2],
              [3, 4],
              [5, 6]
])
B = np.array([7, 8])
print(A.shape)
print(B.shape)

(3, 2)
(2,)


In [21]:
# A : 2차원 배열
# B : 1차원 배열

In [22]:
print(A.ndim)
print(B.ndim)

2
1


In [23]:
# A, B는 차원의 수가 다르다.
# 행렬 곱(내적)이 되는 지 해보자.

In [24]:
print(np.dot(A, B))

[23 53 83]


In [25]:
# 차원의 수가 달라도 shape만 맞으니 행렬 곱(내적)이 되는 것 확인!